Update document object - make preview optional.
Looks like `preview` field should be optional:
```
thread 'main' panicked at 'Failed to get posts.: "Failed to parse VK wall: Error(\"missing field `preview`\", line: 0, column: 0)"', src/main.rs:54:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```